
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAHE
 */
public class book_safari extends javax.swing.JFrame {
    String saf_name;
    public int get_id;
    public static int chng=0;
    /**
     * Creates new form book_safari
     */
    public book_safari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Choose Safari");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter number of seats");

        jButton2.setText("Choose_Safari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jTextField1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        saf_name = (String)jComboBox1.getSelectedItem();
        String tot_seats = jTextField1.getText();
        
        String cus_id = login1.customer_id;
        
        int iid = customer_page1.flag_cus;
       
       String id = Integer.toString(iid);
        
        if(tot_seats.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please enter number of seats");
        }
        else
        {
            try
            {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)
                DriverManager.getConnection("jdbc:mysql://localhost:3306/dbsProj1","root","91069");
                Statement stmt = (Statement)con.createStatement();

                String query = "insert into book_safari(ws_id,name,c_id,tot_seats) values ('"+id+"','"+saf_name+"','"+cus_id+"','"+tot_seats+"');";
                stmt.executeUpdate(query);

                JOptionPane.showMessageDialog(this,"Successfully Added");
                chng=1;
                this.setVisible(false);
                customer_page2 p = new customer_page2();
                p.setVisible(true);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int found=0;        
       int iid = customer_page1.flag_cus;
       
       String id = Integer.toString(iid);
       JOptionPane.showMessageDialog(this,"the value of the id is"+id);
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/dbsproj1","root","91069");
            Statement stmt = (Statement)con.createStatement();
            String query = "Select name from safari where ws_id = '"+id+"';";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                String mo = rs.getString("name");
                jComboBox1.addItem(mo);
                JOptionPane.showMessageDialog(this,"Click Ok to continue");
                found++;
            }
            if(found==0)
            {
                JOptionPane.showMessageDialog(this,"NOt found");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
        if(iid==2)
        {
            jTextArea1.setText("Jeep & Canter Safari is considered the most feasible option to explore the wildlife in Ranthambore. However, spotting the Royal Bengal Tiger resting in their natural habitat depends on your pure luck. Every day, two safaris are conducted for a specified time. The Jeeps & Canters carrying groups of tourists is accompanied by a trained and expert guide are allowed to enter the park with a valid permit. There is a fixed route for the safari inside the park within the appointed time. At a time limited vehicles are allowed into the park for free movemen of sighting."); 


        }
        if(iid==3)
        {
            jTextArea1.setText("");
            jTextArea1.setText("If you want to spot many animals, jeep safari is the best one. For photography, this is the most recommended one. A jeep can accommodate maximum six people. Jeep can be hired for a single person too. A jeep trip stretches for 2 to 3 hours. Jeep night safari is available in the park by some jeep drivers. However, night safari is illegal and it is better to avoid. \n" +
"Bullock cart rides are available through the scrub jungle. People who want to enjoy a picnic in the park choose this option. The park does not provide this ride. It is usually a part of any tour package by resorts near the park. Spotting animals is rare in this region. Bicycle tours are also available during peak tourism season by resorts near the park. Trekkers take up walking tours in the park. ");
        }
        if(iid==4)
        {
            jTextArea1.setText("");
            jTextArea1.setText("There are three types of safaris provided in the park, horse carriage ride, jeep ride and cycle rickshaw ride. Jeep safari is chosen by those who visit to venture deep into the forest and spot animals. You can find jeeps from the entrance of the park. It is usually not preferred by birdwatchers as the sound of the vehicle can scare the birds. If you are planning to choose to ride in a jeep, you are allowed up to 1.7 km inside the park.Jeep safari starts when the park opens and closes during the park’s closing time.");
        }
        if(iid==1)
        {
            jTextArea1.setText("");
            jTextArea1.setText("Explore the richness of Mother Nature at Corbett National Park with jungle safari tours and discover what makes this little gem a paradise for photographers, adventure seekers and wildlife lovers. A safari tour is the best way to come face-to-face with some fiery faces (tiger, jackal, wild boar and Himalayan bear) of the park.\n" +
"There are three types of safaris available in Jim Corbett National Park; Jeep Safari, Elephant Safari and Canter Safari. Among these, jeep and elephant safaris are the most common ones and are available for every zone of the park. But Canter safaris run only in ");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book_safari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book_safari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book_safari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book_safari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book_safari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
